import = ["~/.config/alacritty/solarized_light.toml"]

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/nu"

[window]
option_as_alt = "Both"
