[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config]
documentFormatting = true 
settings.run = "onSave"

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio",  ]

[language-server.pyright.config]
reportMissingTypeStubs = false
reportOptionalMemberAcces = false

[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "ruff", only-features = [ "format", "diagnostics", "code-action" ] },
  { name = "pyright", except-features = [ "format", "diagnostics", "code-action" ] },
]

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m",  "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}"}


[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format=true

[language-server.rust-analyzer.config.check]
command = "clippy"
